@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token ae138375a65d307cd541876e6c8f82920df4ce78

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}
###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/7/
Content-Type: application/json
Authorization: Token 659bd4340d96f3086656f7dae0f5270aeb2394f4

{
  "status": "Закрыто"
}
###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?date_filter_before=2020-10-01
###

# добавление в избранное
POST {{baseUrl}}/advertisements/6/add_to_favourite/
Authorization: Token 659bd4340d96f3086656f7dae0f5270aeb2394f4
###

# фильтрация по всем избранным
GET {{baseUrl}}/advertisements/?in_favourite__user=3