# Generated by Django 5.0.3 on 2024-04-04 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category_categoryarticles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryarticles',
            options={'verbose_name': 'Категория статьи', 'verbose_name_plural': 'Категории статьи'},
        ),
        migrations.AddField(
            model_name='category',
            name='articles',
            field=models.ManyToManyField(related_name='category', through='articles.CategoryArticles', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='categoryarticles',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.category', verbose_name='Категория'),
        ),
    ]
