# Generated by Django 5.0.3 on 2024-04-05 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_tag_remove_categoryarticles_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagarticles',
            old_name='category',
            new_name='tag',
        ),
    ]
