# Generated by Django 5.0.3 on 2024-04-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_category_tagarticles_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(through='articles.TagArticles', to='articles.tag'),
        ),
    ]
