# Generated by Django 5.0.3 on 2024-03-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('author', models.CharField(max_length=64)),
                ('pub_date', models.CharField()),
            ],
        ),
    ]
